### ISSUE TITLE
CSS prefix

### ISSUE THREAD

**Issue by danielkoch** [namics/react-bootstrap-grid-component#5]
What do you think about changing the prefix class or making it configurable.

*I prefer using:*
`g-` instead of `h-`.

 [See also our BEM concept](https://github.com/namics/stylelint-bem-namics#default-pattern-prefixes)

Also you could change the variable name from `$helper-css-prefix` to `$grid-css-prefix`

**Comment by jantimon** [comment]
I am not sure if I understand you correctly where did we use `h-` ?

**Comment by danielkoch** [comment]
Overlooked the [prefix](https://github.com/namics/react-bootstrap-grid-component#prefixes) option. Solves my question.
